google_appliance.settings:
  type: config_object
  label: 'Google Appliance Settings'
  mapping:
    connection_info:
      type: mapping
      label: 'Connection info'
      mapping:
        hostname:
          type: string
        collection:
          type: string
        frontend:
          type: string
        timeout:
          type: integer
    query_param:
      type: mapping
      label: 'Query parameter'
      mapping:
        autofilter:
          type: string
        query_inspection:
          type: boolean
    display_settings:
      type: mapping
      label: 'Display settings'
      mapping:
        drupal_path:
          type: string
        search_title:
          type: string
        results_per_page:
          type: integer
        spelling_suggestions:
          type: boolean
        advanced_search_reporting:
          type: boolean
        sitelinks_search_box:
          type: boolean
        onebox_modules:
          type: sequence
          sequence:
            type: mapping
            mapping:
              value: string
        error_gsa_no_results:
          type: text_format
        error_curl_error:
          type: text_format
        error_lib_xml_parse_error:
          type: text_format
